name: Godot Android APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  export:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 1) JDK 17 để setup-android chạy được
      - name: Set up Java 17 (for Android SDK)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      # 2) Cài Android SDK vào /usr/local/lib/android/sdk
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        env:
          SKIP_JDK_VERSION_CHECK: true

      # 3) Cài gói SDK bắt buộc (license + packages)
      - name: Install Android SDK components
        shell: bash
        env:
          ANDROID_SDK_ROOT: /usr/local/lib/android/sdk
        run: |
          set -e
          SDKMGR="$ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager"

          # Accept licenses (không fail nếu pipe bị ngắt)
          yes | "$SDKMGR" --licenses || true

          # Các gói cần thiết cho Godot 3.x
          "$SDKMGR" --sdk_root="$ANDROID_SDK_ROOT" \
            "platform-tools" \
            "build-tools;33.0.2" \
            "platforms;android-33"

      # 4) Tải Godot 3.5.3 headless + export templates (mirror GitHub ổn định)
      - name: Download Godot headless + templates
        run: |
          mkdir -p "$HOME/.local/share/godot/templates/3.5.3.stable"
          curl -L -o godot.zip https://github.com/godotengine/godot-builds/releases/download/3.5.3-stable/Godot_v3.5.3-stable_linux_headless.64.zip
          unzip -q godot.zip -d godot_bin
          mv godot_bin/Godot_v3.5.3-stable_linux_headless.64 godot
          chmod +x godot
          curl -L -o templates.tpz https://github.com/godotengine/godot-builds/releases/download/3.5.3-stable/Godot_v3.5.3-stable_export_templates.tpz
          unzip -q templates.tpz -d "$HOME/.local/share/godot/templates/3.5.3.stable"

      # 5) Khai báo Android SDK path cho Godot (Editor Settings)
      - name: Configure Godot EditorSettings (SDK path)
        run: |
          ./godot --headless --editor --quit --set android/sdk_path "/usr/local/lib/android/sdk"
          echo "=== editor_settings-3.tres ==="
          cat "$HOME/.config/godot/editor_settings-3.tres" || true

      # 6) Chuyển về JDK 11 cho Gradle của Godot 3.x (ổn định hơn)
      - name: Switch to Java 11 (for Godot Gradle build)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '11'

      # 7) Cài Android Build Template (bắt buộc cho Gradle build)
      - name: Install Android build template
        run: ./godot --headless --path . --quit --install-android-build-template

      # 8) Export APK theo export_presets.cfg
      - name: Export Android APK
        env:
          ANDROID_SDK_ROOT: /usr/local/lib/android/sdk
        run: |
          mkdir -p build/android
          ./godot -v --headless --path . --export "Android" build/android/OfflineRPG.apk
          ls -lah build/android

      # (Tuỳ chọn) Ký APK: tạo 4 secrets rồi bỏ comment 2 bước dưới
      # - name: Decode keystore
      #   if: ${{ secrets.ANDROID_KEYSTORE_BASE64 != '' }}
      #   run: echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 -d > keystore.jks
      #
      # - name: Sign APK
      #   if: ${{ secrets.ANDROID_KEYSTORE_BASE64 != '' }}
      #   uses: r0adkll/sign-android-release@v1
      #   with:
      #     releaseDirectory: build/android
      #     signingKey: keystore.jks
      #     alias: ${{ secrets.ANDROID_KEY_ALIAS }}
      #     keyStorePassword: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
      #     keyPassword: ${{ secrets.ANDROID_KEY_ALIAS_PASSWORD }}

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: OfflineRPG-apk
          path: build/android/*.apk
