name: Godot Android APK (fast non-Gradle, hard-set EditorSettings)

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  export:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Android SDK tối thiểu (chỉ cần ADB để Godot validate)
      - name: Set up Java 17 (for Android SDK)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        env:
          SKIP_JDK_VERSION_CHECK: true

      - name: Install minimal SDK components
        shell: bash
        env:
          ANDROID_SDK_ROOT: /usr/local/lib/android/sdk
        run: |
          set -e
          SDKMGR="$ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager"
          yes | "$SDKMGR" --licenses || true
          "$SDKMGR" --sdk_root="$ANDROID_SDK_ROOT" "platform-tools"
          "$ANDROID_SDK_ROOT/platform-tools/adb" version || true

      # Godot headless + export templates
      - name: Download Godot headless + templates
        run: |
          mkdir -p "$HOME/.local/share/godot/templates/3.5.3.stable"
          curl -L -o godot.zip https://github.com/godotengine/godot-builds/releases/download/3.5.3-stable/Godot_v3.5.3-stable_linux_headless.64.zip
          unzip -q godot.zip -d godot_bin
          mv godot_bin/Godot_v3.5.3-stable_linux_headless.64 godot
          chmod +x godot
          curl -L -o templates.tpz https://github.com/godotengine/godot-builds/releases/download/3.5.3-stable/Godot_v3.5.3-stable_export_templates.tpz
          unzip -q templates.tpz -d "$HOME/.local/share/godot/templates/3.5.3.stable"
          # Đưa android_{debug,release}.apk ra đúng cấp thư mục version
          TDIR="$HOME/.local/share/godot/templates/3.5.3.stable"
          if [ -f "$TDIR/templates/android_debug.apk" ]; then mv "$TDIR/templates/android_debug.apk" "$TDIR/android_debug.apk"; fi
          if [ -f "$TDIR/templates/android_release.apk" ]; then mv "$TDIR/templates/android_release.apk" "$TDIR/android_release.apk"; fi
          ls -lah "$TDIR" || true

      # Tạo debug keystore
      - name: Create Android debug keystore
        run: |
          mkdir -p "$HOME/.android"
          if [ ! -f "$HOME/.android/debug.keystore" ]; then
            keytool -genkeypair -noprompt \
              -alias androiddebugkey \
              -keystore "$HOME/.android/debug.keystore" \
              -storepass android -keypass android \
              -dname "CN=Android Debug,O=Android,C=US" \
              -keyalg RSA -keysize 2048 -validity 10000
          fi
          ls -lah "$HOME/.android"

      # Ghi thẳng EditorSettings với đầy đủ khóa export/android/*
      - name: Write EditorSettings (force)
        env:
          ANDROID_SDK_ROOT: /usr/local/lib/android/sdk
        run: |
          CFG="$HOME/.config/godot"
          mkdir -p "$CFG"
          cat > "$CFG/editor_settings-3.tres" <<EOF
          [gd_resource type="EditorSettings" load_steps=2 format=2]

          [resource]
          export/android/adb = "${ANDROID_SDK_ROOT}/platform-tools/adb"
          export/android/sdk_path = "${ANDROID_SDK_ROOT}"
          export/android/debug_keystore = "${HOME}/.android/debug.keystore"
          export/android/debug_keystore_user = "androiddebugkey"
          export/android/debug_keystore_pass = "android"
          EOF

          echo "=== editor_settings-3.tres ==="
          cat "$CFG/editor_settings-3.tres"

      # Đảm bảo preset Android & tắt Gradle
      - name: Ensure export_presets.cfg (Android preset, non-Gradle)
        run: |
          cat > export_presets.cfg <<'EOF'
          [preset.0]
          name="Android"
          platform="Android"
          runnable=true
          custom_features=""
          export_filter="all_resources"
          include_filter=""
          exclude_filter=""
          export_path="build/android/OfflineRPG.apk"
          script_export_mode=1
          script_encryption_key=""
          advanced_options=false

          [preset.0.options]
          package/unique_name="com.example.offlinerpg"
          version/code=1
          version/name="1.0.0"
          architectures/armeabi-v7a=true
          architectures/arm64-v8a=true
          architectures/x86=false
          architectures/x86_64=false
          gradle_build/use_gradle_build=false
          gradle_build/use_androidx=true
          permissions/Internet=false
          apk_expansion/enable=false
          EOF
          echo "== Presets =="; grep -E '^\[preset|^name=' -n export_presets.cfg || true

      # Export APK (non-Gradle, debug)
      - name: Export Android APK (non-Gradle, debug)
        run: |
          mkdir -p build/android
          ./godot -v --headless --path . --export-debug "Android" build/android/OfflineRPG.apk
          ls -lah build/android

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: OfflineRPG-apk
          path: build/android/*.apk
