name: Godot Android APK (fast non-Gradle)

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  export:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Tải Godot 3.5.3 headless + export templates (không cần Android SDK)
      - name: Download Godot headless + templates
        run: |
          mkdir -p "$HOME/.local/share/godot/templates/3.5.3.stable"
          curl -L -o godot.zip https://github.com/godotengine/godot-builds/releases/download/3.5.3-stable/Godot_v3.5.3-stable_linux_headless.64.zip
          unzip -q godot.zip -d godot_bin
          mv godot_bin/Godot_v3.5.3-stable_linux_headless.64 godot
          chmod +x godot
          curl -L -o templates.tpz https://github.com/godotengine/godot-builds/releases/download/3.5.3-stable/Godot_v3.5.3-stable_export_templates.tpz
          unzip -q templates.tpz -d "$HOME/.local/share/godot/templates/3.5.3.stable"

      # Đảm bảo có preset Android chuẩn và xuất ra build/android/OfflineRPG.apk
      - name: Ensure export_presets.cfg (Android preset)
        run: |
          cat > export_presets.cfg <<'EOF'
          [preset.0]
          name="Android"
          platform="Android"
          runnable=true
          custom_features=""
          export_filter="all_resources"
          include_filter=""
          exclude_filter=""
          export_path="build/android/OfflineRPG.apk"
          script_export_mode=1
          script_encryption_key=""
          advanced_options=false

          [preset.0.options]
          package/unique_name="com.example.offlinerpg"
          version/code=1
          version/name="1.0.0"
          architectures/armeabi-v7a=true
          architectures/arm64-v8a=true
          architectures/x86=false
          architectures/x86_64=false
          # >>> Non-Gradle build (nhanh)
          gradle_build/use_gradle_build=false
          gradle_build/use_androidx=true
          permissions/Internet=false
          apk_expansion/enable=false
          EOF
          echo "== Presets =="
          grep -E '^\[preset|^name=' -n export_presets.cfg || true

      # Export APK nhanh (không dùng Gradle)
      - name: Export Android APK (non-Gradle, debug)
        run: |
          mkdir -p build/android
          ./godot -v --headless --path . --export-debug "Android" build/android/OfflineRPG.apk
          ls -lah build/android

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: OfflineRPG-apk
          path: build/android/*.apk
