name: Godot Android APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Export Godot (Android)
        uses: firebelley/godot-export@v7.0.0
        with:
          use_godot_3: true
          godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/3.5.3/Godot_v3.5.3-stable_linux_headless.64.zip
          godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/3.5.3/Godot_v3.5.3-stable_export_templates.tpz
          relative_project_path: ./
          presets_to_export: "Android"
          use_preset_export_path: true
          cache: true
          verbose: true

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: OfflineRPG-apk
          path: build/android/*.apk
