name: Godot Android APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  export:
    runs-on: ubuntu-latest

    # Image có sẵn Godot 3.5.x + templates + JDK
    container:
      image: barichello/godot-ci:3.5.2
      # Nếu tag này lỗi mạng/tag không có -> dùng fallback:
      # image: barichello/godot-ci:3.5

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show versions
        run: |
          godot -v --version || true
          java -version || true

      # Bắt buộc cho build Gradle của Godot 3: tạo thư mục android/ trong project
      - name: Install Android build template
        run: godot --headless --path . --quit --install-android-build-template

      - name: Export Android APK
        run: |
          mkdir -p build/android
          godot -v --headless --path . --export "Android" build/android/OfflineRPG.apk
          ls -lah build/android || true

      # (Tuỳ chọn) Ký APK — tạo 4 secrets rồi bỏ comment 2 bước dưới:
      # - name: Decode keystore
      #   if: ${{ secrets.ANDROID_KEYSTORE_BASE64 != '' }}
      #   run: echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 -d > keystore.jks
      #
      # - name: Sign APK
      #   if: ${{ secrets.ANDROID_KEYSTORE_BASE64 != '' }}
      #   uses: r0adkll/sign-android-release@v1
      #   with:
      #     releaseDirectory: build/android
      #     signingKey: keystore.jks
      #     alias: ${{ secrets.ANDROID_KEY_ALIAS }}
      #     keyStorePassword: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
      #     keyPassword: ${{ secrets.ANDROID_KEY_ALIAS_PASSWORD }}

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: OfflineRPG-apk
          path: build/android/*.apk
