name: Godot Android APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  export:
    runs-on: ubuntu-latest

    # Dùng image đã có sẵn Godot 3.5.3 + export templates
    container:
      image: barichello/godot-ci:3.5.3   # headless + templates + JDK

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # (Tuỳ chọn) Hiển thị version Godot để debug
      - name: Godot version
        run: godot -v --version

      # Cài Android Build Template vào project (bắt buộc cho build Gradle)
      - name: Install Android build template
        run: |
          godot --headless --path . --quit --install-android-build-template

      # Tạo thư mục output rồi export APK
      - name: Export Android APK
        run: |
          mkdir -p build/android
          godot -v --headless --path . --export "Android" build/android/OfflineRPG.apk

      # (Tuỳ chọn) Ký APK nếu có secrets
      # - name: Decode keystore
      #   if: ${{ secrets.ANDROID_KEYSTORE_BASE64 != '' }}
      #   run: echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 -d > keystore.jks
      # - name: Sign APK
      #   if: ${{ secrets.ANDROID_KEYSTORE_BASE4 != '' }}
      #   uses: r0adkll/sign-android-release@v1
      #   with:
      #     releaseDirectory: build/android
      #     signingKey: keystore.jks
      #     alias: ${{ secrets.ANDROID_KEY_ALIAS }}
      #     keyStorePassword: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
      #     keyPassword: ${{ secrets.ANDROID_KEY_ALIAS_PASSWORD }}

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: OfflineRPG-apk
          path: build/android/*.apk
